In [2]:
import numpy as np

In [8]:
#khai báo mang 1 chieu

In [9]:
a=np.array([1,2,6]) 

In [10]:
a

array([1, 2, 6])

In [11]:
#lay gia tri cua 1 phan tu 

In [12]:
a[1]

2

In [15]:
print('gia tri phan tu thu 2 la',a[1])

gia tri phan tu thu 2 la 2


In [16]:
#kich thuoc cua 1 mang

In [17]:
a.shape

(3,)

In [18]:
#kieu du lieu cua bang 

In [19]:
a.dtype

dtype('int32')

In [20]:
#khai bao mang 2 chieu

In [39]:
a1 = np.array([[1,4,5],[5,7,3],[6,7,4],[3,6,7]])

In [40]:
a1

array([[1, 4, 5],
       [5, 7, 3],
       [6, 7, 4],
       [3, 6, 7]])

In [41]:
print(a1)

[[1 4 5]
 [5 7 3]
 [6 7 4]
 [3 6 7]]


In [42]:
#so phan tu cua mang

In [43]:
a1.size

12

In [44]:
a1.shape

(4, 3)

In [45]:
#so chieu cua mang
a1.ndim

2

In [49]:
#lay phan tu tai vi tri (2,3)
a1[1,2]

3

In [81]:
#khai bao mang co truyen index

In [ ]:
t = 

## phep tinh voi ma tran

In [23]:
x = np.array([[1,2,3],[2,5,3]])
y = np.array([[1,3,2],[5,2,1]])

In [24]:
x

array([[1, 2, 3],
       [2, 5, 3]])

In [25]:
y

array([[1, 3, 2],
       [5, 2, 1]])

In [28]:
np.sum(x)

16

In [53]:
#cong 2 ma tran 

In [54]:
s = x+y

In [55]:
s

array([[2, 5, 5],
       [7, 7, 4]])

In [56]:
np.add(x,y)

array([[2, 5, 5],
       [7, 7, 4]])

In [57]:
# tru 2 ma tran 

In [58]:
sub = x-y

In [59]:
sub

array([[ 0, -1,  1],
       [-3,  3,  2]])

In [60]:
np.subtract(x,y)

array([[ 0, -1,  1],
       [-3,  3,  2]])

In [61]:
#nhan 2 mang tran
multi = x*y 
np.multiply(x,y)

array([[ 1,  6,  6],
       [10, 10,  3]])

In [62]:
multi

array([[ 1,  6,  6],
       [10, 10,  3]])

### Ham Reshape

In [64]:
a2 = np.array([(8,3,4),(4,7,2)])

In [65]:
a2

array([[8, 3, 4],
       [4, 7, 2]])

In [66]:
a2 = a2.reshape(3,2)

In [67]:
a2

array([[8, 3],
       [4, 4],
       [7, 2]])

# slicing

In [74]:
a3 = np.array([[8,10,12],[9,11,13]])

In [75]:
a3

array([[ 8, 10, 12],
       [ 9, 11, 13]])

In [76]:
#lay dong 

In [78]:
a3[0:,].shape

(2, 3)

In [4]:
#ham zeros
np.zeros([2,4], dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [6]:
np.ones([3,3], dtype = float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

random

In [10]:
np.random.random((3,3))

array([[0.76561521, 0.05269393, 0.82010479],
       [0.80352509, 0.54684534, 0.72634906],
       [0.2790048 , 0.75344368, 0.19927902]])

In [12]:
np.random.normal(0,1,(3,3))

array([[ 1.76405235,  0.40015721,  0.97873798],
       [ 2.2408932 ,  1.86755799, -0.97727788],
       [ 0.95008842, -0.15135721, -0.10321885]])

In [16]:
np.random.randint((4,5))

array([1, 1])

In [18]:
np.random.rand(4,5)

array([[0.89603839, 0.63892108, 0.89155444, 0.68005557, 0.44919774],
       [0.97857093, 0.11620191, 0.7670237 , 0.41182014, 0.67543908],
       [0.24979628, 0.31321833, 0.96541622, 0.58846509, 0.65966841],
       [0.53320625, 0.23053302, 0.39486929, 0.61880856, 0.47486752]])

In [27]:
np.concatenate((x,y))

array([[1, 2, 3],
       [2, 5, 3],
       [1, 3, 2],
       [5, 2, 1]])

In [29]:
# gia tri trung binh mean
np.mean(x)

2.6666666666666665

In [30]:
#min,max
np.max(y)

5